# Generated by Django 4.0.4 on 2022-05-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('municao', '0002_alter_municao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
