# Generated by Django 4.0.4 on 2022-05-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_alter_objeto_id'),
        ('armas', '0003_alter_arma_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arma',
            name='calibre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calibre', to='utils.calibre'),
        ),
    ]
