# Generated by Django 4.0.4 on 2022-05-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('tipo_de_objeto', models.CharField(choices=[('38', '38'), ('380', '380'), ('.40', '.40'), ('.45', '.45')], max_length=64)),
            ],
        ),
    ]
