# Generated by Django 4.0.4 on 2022-05-12 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calibre',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_calibre', models.CharField(choices=[('38', '38'), ('380', '380'), ('.40', '.40'), ('.45', '.45')], max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoTipo',
            fields=[
                ('id', models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_objeto', models.CharField(choices=[('Arma', 'Arma'), ('Munição', 'Munição')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('objeto_tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.objetotipo')),
            ],
        ),
    ]
