# Generated by Django 4.0.4 on 2022-05-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_alter_calibre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibre',
            old_name='tipo_de_objeto',
            new_name='desc_calibre',
        ),
    ]
