# Generated by Django 4.0.4 on 2022-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_rename_tipo_de_objeto_calibre_desc_calibre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_objeto', models.CharField(choices=[('Arma', 'Arma'), ('Munição', 'Munição')], max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='calibre',
            name='desc_calibre',
            field=models.CharField(choices=[('38', '38'), ('380', '380'), ('.40', '.40'), ('.45', '.45')], max_length=45),
        ),
    ]
