# Generated by Django 4.0.4 on 2022-05-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibre',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='objetotipo',
            name='id',
            field=models.SmallAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
